core:
  host: anros # suffix -api-route
  app: crm

ui:
  image:
    url: harbor.anrostech.com
    ui: anros/crm-ui:main-1765080557
  hostnames:
    - crm.anrostech.com
  port: "80"
  targetPort: "80"
  pathValue: "/"

server:
  image:
    url: harbor.anrostech.com
    php: anros/crm-server-php:main-1765079577
    nginx: anros/crm-server-nginx:main-1765079577
  api:
    gateway: anrostech # suffix -gateway
    hostnames:
      - api.anrostech.com
    pathValue: "/api"
  port: "80"
  targetPort: "80"
  appUrl: https://anrostech.com
  # need to use sops secrets to encrypt below
  app_key: base64:9Sl6twSf1Iup3In7ysNUdQ18x6r+VB9WwLA5JcrS6XU=
  jwt_secret: gcQR3E52E0e54REAdv0EMohoyhsnNEk5yagQpjcD5vdNqjvTQeh1YpKzG68PxWIY
  jwt_algo: HS256

adminer:
  image: adminer:latest
  hostnames:
    - adminer.anrostech.com

mysql:
  external: false
  image: mysql:8.0
  root_password: AnrosTech01!
  db_connection: mysql
  db_port: "3306"
  db_host: anros-crm-mysql
  # if share is true then disable below for fellows
  # able to change below for each client access
  # need to use sops secrets to encrypt below
  db_username: anros
  db_password: AnrosTech01!
  db_database: anros_crm_db

site:
  hostnames:
    - anrostech.com
    - www.anrostech.com
