apiVersion: apps/v1
kind: Deployment
metadata:
  name: "test-deploy"
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-ui
  template:
    metadata:
      labels:
        app: crm-ui
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: crm-ui
          image: "{{ $.Values.ui.image.url }}/{{ $.Values.ui.image.ui }}"
          ports:
            - containerPort: { { $.Values.ui.targetPort } }

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Values.core.host }}-{{ $.Values.core.app }}-ui-svc"
  namespace: "{{ $.Values.core.host }}-{{ $.Values.core.app }}"
spec:
  type: LoadBalancer # or NodePort/ClusterIP
  selector:
    app: crm-ui
  ports:
    - port: { { $.Values.ui.port } }
      targetPort: { { $.Values.ui.targetPort } }
