apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: test
type: Opaque
data:
  token: Z2l0aHViX3BhdF8xMUJHV0lGQ0kwRlBvbUEwSmFVSFBDX3N6ZUM4V3ZQSGRjYVdxZkxMd1lvbW80RHNuOVpuU2taaGtDc00wakgzckpCVllJQ1k3WWltMlp3cmJi
