apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
  namespace: test
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuYW5yb3N0ZWNoLmNvbSI6eyJhdXRoIjoiWVdSdGFXNDZTR0Z5WW05eU1USXpORFU9IiwiZW1haWwiOiJtYXJrbmd1eWVuYW5sQGdtYWlsLmNvbSJ9fX0=
